import { PromptData } from "@/contexts/PromptContext";

export interface ProjectExportData {
  prompt: PromptData;
  timestamp: string;
  diagrams: {
    sld: string;
    schematic: string;
  };
  bom: Array<{
    component: string;
    model: string;
    qty: number;
    unitPrice: number;
  }>;
  costEstimate: {
    total: number;
    breakdown: Array<{
      item: string;
      cost: number;
    }>;
  };
  safetyReport: {
    passed: number;
    warnings: number;
    failed: number;
    status: string;
  };
}

export function generateProjectReport(promptData: PromptData): string {
  const timestamp = new Date(promptData.timestamp).toLocaleString();
  
  return `# GenVisual AI - Project Report

## Project Information
- **Prompt**: ${promptData.prompt}
- **Industry**: ${promptData.industry}
- **Complexity**: ${promptData.complexity}
- **Generated**: ${timestamp}

## AI Analysis
- **Detected Intent**: ${promptData.intent}
- **Graphic Category**: ${promptData.category}
- **Confidence Score**: ${promptData.confidence}%
- **Estimated Time**: ${promptData.estimatedTime}

## Detected Components
${promptData.components.map((c) => `- ${c}`).join("\n")}

## Bill of Materials (BOM)
| Component | Model | Qty | Unit Price | Total |
|-----------|-------|-----|-----------|-------|
| Motor | 5HP ABB Motor | 1 | ₹5,000 | ₹5,000 |
| Drive | ABB ACS580 | 1 | ₹25,000 | ₹25,000 |
| PLC | ABB AC500 | 1 | ₹25,000 | ₹25,000 |

**Total Project Cost**: ₹55,000

## Safety Compliance
- ✓ Overload Protection: PASS
- ✓ Emergency Stop: PASS
- ✓ Grounding: PASS
- ⚠ Fault Detection: WARNING
- ✗ Safety Interlock: FAIL

## Export Information
This report was automatically generated by GenVisual AI Dashboard.
For more details, visit the dashboard and navigate to each section.
`;
}

export function downloadProjectAsJSON(promptData: PromptData): void {
  const projectData = {
    metadata: {
      version: "1.0",
      exportedAt: new Date().toISOString(),
    },
    prompt: promptData,
    report: generateProjectReport(promptData),
  };

  const dataStr = JSON.stringify(projectData, null, 2);
  const dataBlob = new Blob([dataStr], { type: "application/json" });
  const url = URL.createObjectURL(dataBlob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `GenVisual_Project_${new Date().getTime()}.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function downloadProjectAsCSV(promptData: PromptData): void {
  const csvContent = [
    ["GenVisual AI - Project Export"],
    [""],
    ["Prompt", promptData.prompt],
    ["Industry", promptData.industry],
    ["Complexity", promptData.complexity],
    ["Intent", promptData.intent],
    ["Category", promptData.category],
    ["Confidence", `${promptData.confidence}%`],
    ["Estimated Time", promptData.estimatedTime],
    [""],
    ["Components"],
    ...promptData.components.map((c) => [c]),
    [""],
    ["Bill of Materials"],
    ["Component", "Model", "Qty", "Unit Price", "Total"],
    ["Motor", "5HP ABB Motor", "1", "₹5,000", "₹5,000"],
    ["Drive", "ABB ACS580", "1", "₹25,000", "₹25,000"],
    ["PLC", "ABB AC500", "1", "₹25,000", "₹25,000"],
  ]
    .map((row) => row.map((cell) => `"${cell}"`).join(","))
    .join("\n");

  const dataBlob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(dataBlob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `GenVisual_Project_${new Date().getTime()}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function downloadProjectAsMarkdown(promptData: PromptData): void {
  const markdownContent = generateProjectReport(promptData);
  const dataBlob = new Blob([markdownContent], { type: "text/markdown" });
  const url = URL.createObjectURL(dataBlob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `GenVisual_Project_${new Date().getTime()}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
