import { PromptData } from "@/contexts/PromptContext";
import {
  generateBOMComponents,
  generateSafetyChecks,
  generateCostBreakdown,
} from "@/lib/promptAnalyzer";

export function generateProjectReport(promptData: PromptData): string {
  const timestamp = new Date(promptData.timestamp || Date.now()).toLocaleString();
  const bom = generateBOMComponents(promptData);
  const safetyChecks = generateSafetyChecks(promptData);
  const costs = generateCostBreakdown(promptData);
  const totalCost = costs.reduce((sum, item) => sum + item.cost, 0);

  const bomRows = bom
    .map(
      (item) =>
        `| ${item.name} | ${item.model} | ${item.qty} | ₹${item.unitPrice.toLocaleString()} | ₹${item.totalPrice.toLocaleString()} |`
    )
    .join("\n");

  const safetyRows = safetyChecks
    .map(
      (check) =>
        `- ${check.status === "pass" ? "✓" : check.status === "warning" ? "⚠" : "✗"} **${check.name}**: ${check.status.toUpperCase()} (${check.description})`
    )
    .join("\n");

  return `# GenVisual AI - Engineering Project Report

## Project Metadata
- **Prompt**: ${promptData.prompt}
- **Industry**: ${promptData.industry}
- **Complexity Tier**: ${promptData.complexity}
- **Generated**: ${timestamp}

## AI Analysis Summary
- **Detected Intent**: ${promptData.intent}
- **Graphic Category**: ${promptData.category}
- **Confidence Score**: ${promptData.confidence}%
- **Estimated Build Time**: ${promptData.estimatedTime}

## Detected Components
${promptData.components.map((c) => `- ${c}`).join("\n")}

## Bill of Materials (BOM)
| Component | Model | Qty | Unit Price | Total |
|-----------|-------|-----|-----------|-------|
${bomRows}

**Total Estimated Project Cost**: ₹${totalCost.toLocaleString()}

## Safety & Compliance Audit
${safetyRows}

## System Specifications
- **Operating Voltage**: 415V 3-Phase AC / 24VDC Control
- **Control Architecture**: ${promptData.complexity} Grade System
- **Standards Compliance**: IEEE / IEC / ISO ${promptData.industry} Regulations

---
*Report automatically generated by GenVisual AI Dashboard.*
`;
}

export function downloadProjectAsJSON(promptData: PromptData): void {
  const bom = generateBOMComponents(promptData);
  const safetyChecks = generateSafetyChecks(promptData);
  const costs = generateCostBreakdown(promptData);

  const projectData = {
    metadata: {
      version: "1.0",
      exportedAt: new Date().toISOString(),
      generator: "GenVisual AI Dashboard",
    },
    prompt: promptData,
    bom,
    safetyChecks,
    costBreakdown: costs,
    totalCost: costs.reduce((sum, c) => sum + c.cost, 0),
    reportText: generateProjectReport(promptData),
  };

  const dataStr = JSON.stringify(projectData, null, 2);
  const dataBlob = new Blob([dataStr], { type: "application/json" });
  const url = URL.createObjectURL(dataBlob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `GenVisual_Project_${promptData.industry.replace(/\s+/g, "_")}_${new Date().getTime()}.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function downloadProjectAsCSV(promptData: PromptData): void {
  const bom = generateBOMComponents(promptData);
  const costs = generateCostBreakdown(promptData);

  const csvRows = [
    ["GenVisual AI - Project Export"],
    [""],
    ["Prompt", promptData.prompt],
    ["Industry", promptData.industry],
    ["Complexity", promptData.complexity],
    ["Intent", promptData.intent],
    ["Category", promptData.category],
    ["Confidence", `${promptData.confidence}%`],
    ["Estimated Time", promptData.estimatedTime],
    [""],
    ["Detected Components"],
    ...promptData.components.map((c) => [c]),
    [""],
    ["Bill of Materials"],
    ["Component", "Model", "Qty", "Unit Price", "Total"],
    ...bom.map((b) => [b.name, b.model, b.qty.toString(), `₹${b.unitPrice}`, `₹${b.totalPrice}`]),
    [""],
    ["Cost Breakdown"],
    ["Category", "Cost"],
    ...costs.map((c) => [c.item, `₹${c.cost}`]),
  ];

  const csvContent = csvRows
    .map((row) => row.map((cell) => `"${cell}"`).join(","))
    .join("\n");

  const dataBlob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(dataBlob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `GenVisual_Project_${promptData.industry.replace(/\s+/g, "_")}_${new Date().getTime()}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function downloadProjectAsMarkdown(promptData: PromptData): void {
  const markdownContent = generateProjectReport(promptData);
  const dataBlob = new Blob([markdownContent], { type: "text/markdown" });
  const url = URL.createObjectURL(dataBlob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `GenVisual_Project_${promptData.industry.replace(/\s+/g, "_")}_${new Date().getTime()}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
